export type MockServerData = {
  titles: string[],
  descriptions: string[],
  cities: string[],
  previewImages: string[],
  images: string[],
  isPremium: string[],
  isFavorite: string[],
  rating: string[],
  type: string[],
  rooms: string[],
  guests: string[],
  amenities: string[],
  names: string[],
  emails: string[],
  avatars: string[],
  passwords: string[],
  userType: string[],
  commentsCount: string[],
  coordinates: string[][],
}
